# Makefile for the VERSEM Python suite
#
#
.PHONY: all init test docs clean


all: init test docs

# Initializing installation
init:
	pip install -r requirements.txt

# Testing installation
test:
	py.test tests

# Make Documentation
docs:
	make clean -C docs
	make clean -C docs/source/autogenerated
	sphinx-apidoc -o ./docs/source/autogenerated/src ./src [*.rst *.npy]
	sphinx-apidoc -o ./docs/source/autogenerated/tests ./tests [*.rst *.npy]
	sphinx-apidoc -o ./docs/source/autogenerated/input ./input [*.rst *.npy]
	sphinx-apidoc -o ./docs/source/autogenerated/scripts ./scripts [*.rst *.npy]
	make html -C docs

# If Latex wanted
latexpdf: docs
	make latexpdf -C docs

# Recompile html
html: docs
	make html -C docs

# Clean documents
cleandocs:
	make clean -C docs
	make clean -C docs/source/autogenerated

# Cleaning up
cleanresults:
	rm -rf results/*
	
# Clean all
clean:
	make cleandocs
	make cleanresults


